package com.studykt.entity;

import java.util.Date;

public class CourseVideo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_video.id
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_video.course_id
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_video.title
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_video.cover_url
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_video.source_url
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_video.create_time
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_video.id
     *
     * @return the value of course_video.id
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_video.id
     *
     * @param id the value for course_video.id
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_video.course_id
     *
     * @return the value of course_video.course_id
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_video.course_id
     *
     * @param courseId the value for course_video.course_id
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_video.title
     *
     * @return the value of course_video.title
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_video.title
     *
     * @param title the value for course_video.title
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_video.cover_url
     *
     * @return the value of course_video.cover_url
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_video.cover_url
     *
     * @param coverUrl the value for course_video.cover_url
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_video.source_url
     *
     * @return the value of course_video.source_url
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_video.source_url
     *
     * @param sourceUrl the value for course_video.source_url
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_video.create_time
     *
     * @return the value of course_video.create_time
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_video.create_time
     *
     * @param createTime the value for course_video.create_time
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}