package com.studykt.entity;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.title
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.introduction
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_name
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_avatar_url
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String teacherAvatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cover_url
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.study_count
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private Integer studyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_date
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_introduction
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    private String teacherIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title
     *
     * @return the value of course.title
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title
     *
     * @param title the value for course.title
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.introduction
     *
     * @return the value of course.introduction
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.introduction
     *
     * @param introduction the value for course.introduction
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_name
     *
     * @return the value of course.teacher_name
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_name
     *
     * @param teacherName the value for course.teacher_name
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_avatar_url
     *
     * @return the value of course.teacher_avatar_url
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getTeacherAvatarUrl() {
        return teacherAvatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_avatar_url
     *
     * @param teacherAvatarUrl the value for course.teacher_avatar_url
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setTeacherAvatarUrl(String teacherAvatarUrl) {
        this.teacherAvatarUrl = teacherAvatarUrl == null ? null : teacherAvatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cover_url
     *
     * @return the value of course.cover_url
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cover_url
     *
     * @param coverUrl the value for course.cover_url
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.study_count
     *
     * @return the value of course.study_count
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public Integer getStudyCount() {
        return studyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.study_count
     *
     * @param studyCount the value for course.study_count
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setStudyCount(Integer studyCount) {
        this.studyCount = studyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_date
     *
     * @return the value of course.create_date
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_date
     *
     * @param createDate the value for course.create_date
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_introduction
     *
     * @return the value of course.teacher_introduction
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public String getTeacherIntroduction() {
        return teacherIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_introduction
     *
     * @param teacherIntroduction the value for course.teacher_introduction
     *
     * @mbg.generated Wed Apr 14 21:56:20 CST 2021
     */
    public void setTeacherIntroduction(String teacherIntroduction) {
        this.teacherIntroduction = teacherIntroduction == null ? null : teacherIntroduction.trim();
    }
}