package com.studykt.entity;

import java.util.Date;

public class CourseComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.course_id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.user_id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.content
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.score
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.create_time
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.status
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.like_count
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    private Integer likeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.id
     *
     * @return the value of course_comment.id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.id
     *
     * @param id the value for course_comment.id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.course_id
     *
     * @return the value of course_comment.course_id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.course_id
     *
     * @param courseId the value for course_comment.course_id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.user_id
     *
     * @return the value of course_comment.user_id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.user_id
     *
     * @param userId the value for course_comment.user_id
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.content
     *
     * @return the value of course_comment.content
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.content
     *
     * @param content the value for course_comment.content
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.score
     *
     * @return the value of course_comment.score
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.score
     *
     * @param score the value for course_comment.score
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.create_time
     *
     * @return the value of course_comment.create_time
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.create_time
     *
     * @param createTime the value for course_comment.create_time
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.status
     *
     * @return the value of course_comment.status
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.status
     *
     * @param status the value for course_comment.status
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.like_count
     *
     * @return the value of course_comment.like_count
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.like_count
     *
     * @param likeCount the value for course_comment.like_count
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}