package com.studykt.entity;

import java.util.Date;

public class Feedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.id
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.user_id
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.content
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.create_time
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.process_status
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    private Integer processStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.contact
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    private String contact;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.id
     *
     * @return the value of feedback.id
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.id
     *
     * @param id the value for feedback.id
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.user_id
     *
     * @return the value of feedback.user_id
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.user_id
     *
     * @param userId the value for feedback.user_id
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.create_time
     *
     * @return the value of feedback.create_time
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.create_time
     *
     * @param createTime the value for feedback.create_time
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.process_status
     *
     * @return the value of feedback.process_status
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public Integer getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.process_status
     *
     * @param processStatus the value for feedback.process_status
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.contact
     *
     * @return the value of feedback.contact
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.contact
     *
     * @param contact the value for feedback.contact
     *
     * @mbg.generated Sat May 01 17:42:51 CST 2021
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }
}