package com.studykt.entity;

public class Problem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.id
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.type
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.category
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.p_index
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private Integer pIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.ano_index
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private Integer anoIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.content
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.analysis
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private String analysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.browse_count
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    private Integer browseCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.id
     *
     * @return the value of problem.id
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.id
     *
     * @param id the value for problem.id
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.type
     *
     * @return the value of problem.type
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.type
     *
     * @param type the value for problem.type
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.category
     *
     * @return the value of problem.category
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.category
     *
     * @param category the value for problem.category
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.p_index
     *
     * @return the value of problem.p_index
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public Integer getpIndex() {
        return pIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.p_index
     *
     * @param pIndex the value for problem.p_index
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setpIndex(Integer pIndex) {
        this.pIndex = pIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.ano_index
     *
     * @return the value of problem.ano_index
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public Integer getAnoIndex() {
        return anoIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.ano_index
     *
     * @param anoIndex the value for problem.ano_index
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setAnoIndex(Integer anoIndex) {
        this.anoIndex = anoIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.content
     *
     * @return the value of problem.content
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.content
     *
     * @param content the value for problem.content
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.analysis
     *
     * @return the value of problem.analysis
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.analysis
     *
     * @param analysis the value for problem.analysis
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.browse_count
     *
     * @return the value of problem.browse_count
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public Integer getBrowseCount() {
        return browseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.browse_count
     *
     * @param browseCount the value for problem.browse_count
     *
     * @mbg.generated Fri Apr 30 14:36:07 CST 2021
     */
    public void setBrowseCount(Integer browseCount) {
        this.browseCount = browseCount;
    }
}