package com.studykt.entity;

public class ProblemOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem_option.id
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem_option.problem_id
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    private String problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem_option.opt_index
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    private Integer optIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem_option.content
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem_option.id
     *
     * @return the value of problem_option.id
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem_option.id
     *
     * @param id the value for problem_option.id
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem_option.problem_id
     *
     * @return the value of problem_option.problem_id
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public String getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem_option.problem_id
     *
     * @param problemId the value for problem_option.problem_id
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public void setProblemId(String problemId) {
        this.problemId = problemId == null ? null : problemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem_option.opt_index
     *
     * @return the value of problem_option.opt_index
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public Integer getOptIndex() {
        return optIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem_option.opt_index
     *
     * @param optIndex the value for problem_option.opt_index
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public void setOptIndex(Integer optIndex) {
        this.optIndex = optIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem_option.content
     *
     * @return the value of problem_option.content
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem_option.content
     *
     * @param content the value for problem_option.content
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}