package com.studykt.entity;

import java.util.Date;

public class SearchTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_tag.id
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_tag.tag_name
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_tag.create_time
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_tag.id
     *
     * @return the value of search_tag.id
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_tag.id
     *
     * @param id the value for search_tag.id
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_tag.tag_name
     *
     * @return the value of search_tag.tag_name
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_tag.tag_name
     *
     * @param tagName the value for search_tag.tag_name
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_tag.create_time
     *
     * @return the value of search_tag.create_time
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_tag.create_time
     *
     * @param createTime the value for search_tag.create_time
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}