package com.studykt.entity;

import java.util.Date;

public class SearchRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.id
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.content
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.create_date
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.id
     *
     * @return the value of search_record.id
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.id
     *
     * @param id the value for search_record.id
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.content
     *
     * @return the value of search_record.content
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.content
     *
     * @param content the value for search_record.content
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.create_date
     *
     * @return the value of search_record.create_date
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.create_date
     *
     * @param createDate the value for search_record.create_date
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}