package com.studykt.entity;

import java.util.Date;

public class StudyRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_record.id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_record.user_id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_record.course_id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_record.study_duration
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    private Double studyDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_record.start_date
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_record.end_date
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_record.id
     *
     * @return the value of study_record.id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_record.id
     *
     * @param id the value for study_record.id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_record.user_id
     *
     * @return the value of study_record.user_id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_record.user_id
     *
     * @param userId the value for study_record.user_id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_record.course_id
     *
     * @return the value of study_record.course_id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_record.course_id
     *
     * @param courseId the value for study_record.course_id
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_record.study_duration
     *
     * @return the value of study_record.study_duration
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public Double getStudyDuration() {
        return studyDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_record.study_duration
     *
     * @param studyDuration the value for study_record.study_duration
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public void setStudyDuration(Double studyDuration) {
        this.studyDuration = studyDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_record.start_date
     *
     * @return the value of study_record.start_date
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_record.start_date
     *
     * @param startDate the value for study_record.start_date
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_record.end_date
     *
     * @return the value of study_record.end_date
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_record.end_date
     *
     * @param endDate the value for study_record.end_date
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}