package com.studykt.entity;

import java.util.Date;

public class TestResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.id
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.user_id
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.subject
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.problem_count
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private Integer problemCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.correct_count
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private Integer correctCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.percent
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private Double percent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.create_date
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.id
     *
     * @return the value of test_result.id
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.id
     *
     * @param id the value for test_result.id
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.user_id
     *
     * @return the value of test_result.user_id
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.user_id
     *
     * @param userId the value for test_result.user_id
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.subject
     *
     * @return the value of test_result.subject
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.subject
     *
     * @param subject the value for test_result.subject
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.problem_count
     *
     * @return the value of test_result.problem_count
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public Integer getProblemCount() {
        return problemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.problem_count
     *
     * @param problemCount the value for test_result.problem_count
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setProblemCount(Integer problemCount) {
        this.problemCount = problemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.correct_count
     *
     * @return the value of test_result.correct_count
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public Integer getCorrectCount() {
        return correctCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.correct_count
     *
     * @param correctCount the value for test_result.correct_count
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setCorrectCount(Integer correctCount) {
        this.correctCount = correctCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.percent
     *
     * @return the value of test_result.percent
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public Double getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.percent
     *
     * @param percent the value for test_result.percent
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setPercent(Double percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.create_date
     *
     * @return the value of test_result.create_date
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.create_date
     *
     * @param createDate the value for test_result.create_date
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}