package com.studykt.entity;

import java.util.Date;

public class UserCourseHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_history.id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_history.user_id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_history.course_id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_history.create_date
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_history.id
     *
     * @return the value of user_course_history.id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_history.id
     *
     * @param id the value for user_course_history.id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_history.user_id
     *
     * @return the value of user_course_history.user_id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_history.user_id
     *
     * @param userId the value for user_course_history.user_id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_history.course_id
     *
     * @return the value of user_course_history.course_id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_history.course_id
     *
     * @param courseId the value for user_course_history.course_id
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_history.create_date
     *
     * @return the value of user_course_history.create_date
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_history.create_date
     *
     * @param createDate the value for user_course_history.create_date
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}