package com.studykt.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel(value = "User", description = "用户对象")
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.openid
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "openid", name = "openid", example = "openid", required = true)
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.nick_name
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "nickName", name = "nickName", example = "test", required = false)
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.avatar_url
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(hidden = true)
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.gender
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "gender", name = "gender", example = "1", required = false)
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.country
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "country", name = "country", example = "China", required = false)
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.province
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "province", name = "province", example = "HuBei", required = false)
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.city
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "city", name = "city", example = "WuHan", required = false)
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.language
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(value = "language", name = "language", example = "ZH_CN", required = false)
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.last_update_time
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    @ApiModelProperty(hidden = true)
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.openid
     *
     * @return the value of wx_user.openid
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.openid
     *
     * @param openid the value for wx_user.openid
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.nick_name
     *
     * @return the value of wx_user.nick_name
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.nick_name
     *
     * @param nickName the value for wx_user.nick_name
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.avatar_url
     *
     * @return the value of wx_user.avatar_url
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.avatar_url
     *
     * @param avatarUrl the value for wx_user.avatar_url
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.gender
     *
     * @return the value of wx_user.gender
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.gender
     *
     * @param gender the value for wx_user.gender
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.country
     *
     * @return the value of wx_user.country
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.country
     *
     * @param country the value for wx_user.country
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.province
     *
     * @return the value of wx_user.province
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.province
     *
     * @param province the value for wx_user.province
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.city
     *
     * @return the value of wx_user.city
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.city
     *
     * @param city the value for wx_user.city
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.language
     *
     * @return the value of wx_user.language
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.language
     *
     * @param language the value for wx_user.language
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.last_update_time
     *
     * @return the value of wx_user.last_update_time
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.last_update_time
     *
     * @param lastUpdateTime the value for wx_user.last_update_time
     *
     * @mbg.generated Wed Apr 07 21:34:16 CST 2021
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}