package com.studykt.entity;

import java.util.Date;

public class UserFavorCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_favor_course.id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_favor_course.user_id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_favor_course.course_id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_favor_course.favor_date
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    private Date favorDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_favor_course.progress
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    private Double progress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_favor_course.id
     *
     * @return the value of user_favor_course.id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_favor_course.id
     *
     * @param id the value for user_favor_course.id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_favor_course.user_id
     *
     * @return the value of user_favor_course.user_id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_favor_course.user_id
     *
     * @param userId the value for user_favor_course.user_id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_favor_course.course_id
     *
     * @return the value of user_favor_course.course_id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_favor_course.course_id
     *
     * @param courseId the value for user_favor_course.course_id
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_favor_course.favor_date
     *
     * @return the value of user_favor_course.favor_date
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public Date getFavorDate() {
        return favorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_favor_course.favor_date
     *
     * @param favorDate the value for user_favor_course.favor_date
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public void setFavorDate(Date favorDate) {
        this.favorDate = favorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_favor_course.progress
     *
     * @return the value of user_favor_course.progress
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public Double getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_favor_course.progress
     *
     * @param progress the value for user_favor_course.progress
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    public void setProgress(Double progress) {
        this.progress = progress;
    }
}