package com.studykt.mapper;

import com.studykt.entity.CourseComment;
import com.studykt.entity.CourseCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    long countByExample(CourseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int deleteByExample(CourseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int insert(CourseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int insertSelective(CourseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    List<CourseComment> selectByExample(CourseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    CourseComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") CourseComment record, @Param("example") CourseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int updateByExample(@Param("record") CourseComment record, @Param("example") CourseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int updateByPrimaryKeySelective(CourseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_comment
     *
     * @mbg.generated Mon Apr 26 16:58:32 CST 2021
     */
    int updateByPrimaryKey(CourseComment record);
}