package com.studykt.mapper;

import com.studykt.entity.CourseVideo;
import com.studykt.entity.CourseVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    long countByExample(CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int deleteByExample(CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int insert(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int insertSelective(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    List<CourseVideo> selectByExample(CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    CourseVideo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") CourseVideo record, @Param("example") CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int updateByExample(@Param("record") CourseVideo record, @Param("example") CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int updateByPrimaryKeySelective(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Fri Apr 09 22:13:39 CST 2021
     */
    int updateByPrimaryKey(CourseVideo record);
}