package com.studykt.mapper;

import com.studykt.entity.ProblemOption;
import com.studykt.entity.ProblemOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProblemOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    long countByExample(ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int deleteByExample(ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int insert(ProblemOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int insertSelective(ProblemOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    List<ProblemOption> selectByExampleWithBLOBs(ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    List<ProblemOption> selectByExample(ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    ProblemOption selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") ProblemOption record, @Param("example") ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ProblemOption record, @Param("example") ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int updateByExample(@Param("record") ProblemOption record, @Param("example") ProblemOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int updateByPrimaryKeySelective(ProblemOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ProblemOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem_option
     *
     * @mbg.generated Fri Apr 30 13:45:49 CST 2021
     */
    int updateByPrimaryKey(ProblemOption record);


    List<String> selectContentByProblemId(String problemId);
}