package com.studykt.mapper;

import com.studykt.entity.SearchRecord;
import com.studykt.entity.SearchRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    long countByExample(SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int deleteByExample(SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int insert(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int insertSelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    List<SearchRecord> selectByExample(SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    SearchRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") SearchRecord record, @Param("example") SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int updateByExample(@Param("record") SearchRecord record, @Param("example") SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int updateByPrimaryKeySelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue Apr 20 15:18:04 CST 2021
     */
    int updateByPrimaryKey(SearchRecord record);



    List<String> selectContentOrderByCount(Integer numOfRecords);
}