package com.studykt.mapper;

import com.studykt.entity.SearchTag;
import com.studykt.entity.SearchTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    long countByExample(SearchTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int deleteByExample(SearchTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int insert(SearchTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int insertSelective(SearchTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    List<SearchTag> selectByExample(SearchTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    SearchTag selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") SearchTag record, @Param("example") SearchTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int updateByExample(@Param("record") SearchTag record, @Param("example") SearchTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int updateByPrimaryKeySelective(SearchTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_tag
     *
     * @mbg.generated Sat Apr 24 12:47:02 CST 2021
     */
    int updateByPrimaryKey(SearchTag record);


    List<String> selectTagOrderByCount(Integer numOfRecords);
}