package com.studykt.mapper;

import com.studykt.entity.StudyRecord;
import com.studykt.entity.StudyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    long countByExample(StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int deleteByExample(StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int insert(StudyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int insertSelective(StudyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    List<StudyRecord> selectByExample(StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    StudyRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int updateByExampleSelective(@Param("record") StudyRecord record, @Param("example") StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int updateByExample(@Param("record") StudyRecord record, @Param("example") StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int updateByPrimaryKeySelective(StudyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbg.generated Wed Apr 28 16:21:10 CST 2021
     */
    int updateByPrimaryKey(StudyRecord record);



    Integer selectStudyDurationSumByUserId(String userId);
}