package com.studykt.mapper;

import com.studykt.entity.TestResult;
import com.studykt.entity.TestResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    long countByExample(TestResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int deleteByExample(TestResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int insert(TestResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int insertSelective(TestResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    List<TestResult> selectByExample(TestResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    TestResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") TestResult record, @Param("example") TestResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int updateByExample(@Param("record") TestResult record, @Param("example") TestResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int updateByPrimaryKeySelective(TestResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated Fri Apr 30 20:52:59 CST 2021
     */
    int updateByPrimaryKey(TestResult record);
}