package com.studykt.mapper;

import com.studykt.entity.UserCourseHistory;
import com.studykt.entity.UserCourseHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCourseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    long countByExample(UserCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int deleteByExample(UserCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int insert(UserCourseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int insertSelective(UserCourseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    List<UserCourseHistory> selectByExample(UserCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    UserCourseHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserCourseHistory record, @Param("example") UserCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int updateByExample(@Param("record") UserCourseHistory record, @Param("example") UserCourseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int updateByPrimaryKeySelective(UserCourseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_history
     *
     * @mbg.generated Tue Apr 13 14:27:05 CST 2021
     */
    int updateByPrimaryKey(UserCourseHistory record);
}