package com.studykt.mapper;

import com.studykt.entity.UserFavorCourse;
import com.studykt.entity.UserFavorCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFavorCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    long countByExample(UserFavorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int deleteByExample(UserFavorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int insert(UserFavorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int insertSelective(UserFavorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    List<UserFavorCourse> selectByExample(UserFavorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    UserFavorCourse selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserFavorCourse record, @Param("example") UserFavorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int updateByExample(@Param("record") UserFavorCourse record, @Param("example") UserFavorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int updateByPrimaryKeySelective(UserFavorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favor_course
     *
     * @mbg.generated Fri Apr 16 21:29:08 CST 2021
     */
    int updateByPrimaryKey(UserFavorCourse record);
}